version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    cmake: "3.22"
    # You can also specify other tool versions:
    # nodejs: "16"
  commands:
    - cmake -B build -S . -DBUILD_DOCS=ON # Configure CMake
    - cmake --build build --target Doxygen Sphinx # Build project

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Dependencies required to build your docs
python:
   install:
   - requirements: docs/requirements.txt