name: Build source distribution
# Build the source distribution under Linux

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install -y libeigen3-dev libglpk-dev
          python -m pip install numpy scipy
          python -m pip install twine build

      - name: Build source distribution
        run: |
          python -m build --sdist
          # Check whether the source distribution will render correctly
          twine check dist/*.tar.gz

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz




