name: Build CI wheels

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13, macos-14, windows-2022] 
# macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # Skip 32-bit builds and musllinux
          CIBW_SKIP: "*-win32 *-manylinux_i686 *musllinux*"
          CIBW_BEFORE_ALL_MACOS: |
            brew install eigen ipopt
            git clone https://github.com/ethz-adrl/ifopt.git && cd ifopt
            mkdir build && cd build
            cmake ..
            make
            sudo make install
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y epel-release eigen3-devel coin-or-Ipopt-devel
            # rpm -ql coin-or-Ipopt-devel
            git clone https://github.com/ethz-adrl/ifopt.git && cd ifopt
            mkdir build && cd build
            cmake ..
            make
            make install
          CIBW_BEFORE_ALL_WINDOWS: "bash .github/workflows/scripts/windows-setup.sh"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: '{package}/pyproject.toml'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
