name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'   # Matches tags like v1.0, v2.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/polytopewalk

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the wheels / dists
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/